name: Publish Any Commit

on:
  pull_request:
  push:
    branches:
      - "**"
    tags:
      - "!**"
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Build
        run: pnpm exec nx build plugins-spellcheck

      - run: pnpm dlx pkg-pr-new publish './dist/packages/plugins/spellcheck'
